_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 37
                - 55
                - 82
            "2":
                - 1
                - 37
                - 55
                - 82
            "3":
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.9.19
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
